### ISSUE TITLE
INCR with initial TTL

### ISSUE THREAD

**Issue by alexist** [grrolland/ngx-distributed-shm#24]
Hi,

The [lua.shared](https://github.com/openresty/lua-nginx-module#ngxshareddict) semantic has evolved. The method [incr](https://github.com/openresty/lua-nginx-module#ngxshareddictincr) now accept an optional parameter init_ttl :

`syntax: newval, err, forcible? = ngx.shared.DICT:incr(key, value, init?, init_ttl?)`

init_ttl allow to create the missing key with a ttl and avoid to make another call to handle expiration (incr than expire)

`remaining, err = dict:incr(key, -1, limit, window)`

I can submit a PR to add this new optional parameter in ngx-distributed-shm

**Comment by grrolland** [comment]
Thanks for your PR.
