### ISSUE TITLE
IncrProcessor executed on each backup

### ISSUE THREAD

**Issue by alexist** [grrolland/ngx-distributed-shm#27]
Hi,

When deployed in a cluster with backup-count greater than 0, IncrCommand is executed on each backup. For example, with 1 backup;
```
INCR KEY 1 1
LEN 1
1
DONE
GET KEY
LEN 1
3
DONE
```
 

The issue is related to this line in IncrCommand :
```java
map.set(entry.getKey(), new ShmValue(newval, expire), expire, TimeUnit.SECONDS);
```
This code fix the issue :
```java
ExtendedMapEntry<String, ShmValue> extendedMapEntry = (ExtendedMapEntry<String, ShmValue>) entry
extendedMapEntry.setValue(new ShmValue(newval, expire), expire, TimeUnit.SECONDS);
```

This is documented in Javadoc :
`The entry's value will be null, if the entry for the key doesn't exist. You can create new mapping by setting a non-null value or remove existing mapping entry by setting the value to null.`

**Comment by grrolland** [comment]
Merged
