### ISSUE TITLE
Memory consumption and probes

### ISSUE THREAD

**Issue by sgandon** [grrolland/ngx-distributed-shm#7]
Hello,
We are thinking of using dshm with openresty in order to cache our web app sessions among multiple instances in a Kubernetes environment.
You provide some Kubernetes manifest example which is nice but in terms of production readyness I was wondering if you could provide some guidance in the RAM requirements for the container (Requests and limits).
I would also like to ask if it is possible to setup some kind of readyness and liveness probe as well ?

**Comment by grrolland** [comment]
Hi,

I have made some tests using the first production ready version of DSHM. With a 2 node installation (2 openresty + 2 dshm) on two 2vCPU 4Go RAM virtual machine (DSHM configured with 512Mb heap), I run 1000 request/s scénario with OIDC session caching.
The sizing of the DSHM heap depends your webapp sessions size (with huge session you need more heap).

Concerning readyness and liveness, you can use curl+telnet or netcat command to check the port is open (when the port is open, DSHM is ready), connect to the port and send a QUIT command, then expect the connection is closed. In this case the server is responding and is alive and ready.

Regards,
